# Use 'createuser -s postgres' to create a general purpose db (super)user.

development: &default
  adapter: postgresql
  encoding: utf8
  database: foreningflex_development
  username: foreningflex
  password: foreningflex
  pool: 5
  timeout: 5000
  host: localhost

test:
  <<: *default
  database: foreningflex_test
  min_messages: warning

production:
  <<: *default
  database: foreningflex_production

proxied-console:
  adapter: postgresql 
  database : d10d455e42bbb49c097d525cc1eada896
  username : ub24a96d740314d9aa83935e9024e5021
  password : p61d09f8e8bad47469121f9c42683cdfc
  port: 10000 
  host: 127.0.0.1  
